#pragma once

// ──────────────────────────────────────────────────────────────
// What this product is, and how it is meant to be driven - in the product's own
// words, in the application layer, beside the managers the words are about.
//
// It lives here and not in the relay for one reason: whatever answers "how do I
// use this device" has to be the firmware that is actually running. A copy kept
// server-side is a copy that describes last month's build, and the one caller
// who cannot notice is the one most likely to act on it.
//
// Registered into the framework from AppContext::Init() (see
// SystemManager::SetDocumentation). Strux never reaches up for it.
//
//   DESCRIPTION   one line. It rides in the relay hello, so it is in a device
//                 list before anything asks the device a question.
//   INSTRUCTIONS  free-form, served on request (`system describe`). Prose and
//                 NOT a schema: every command already declares its own name,
//                 arguments and types through `help describe`. This is for what
//                 never fits in a declaration - which commands belong together,
//                 what order they go in, and what will not work.
//
// ASCII ONLY in these literals. GCC's execution charset follows the build
// host's locale, so a UTF-8 dash here leaves this machine as one cp1252 byte -
// invalid UTF-8 in the JSON reply, and invisible in review.
// ──────────────────────────────────────────────────────────────
namespace DeviceDoc {

inline constexpr const char* DESCRIPTION =
    "Lablr - a label printer. It stores SVG label designs on its own "
    "filesystem, renders them, and prints them on a DYMO LabelWriter over "
    "USB.";

inline constexpr const char* INSTRUCTIONS =
    "Lablr renders labels. A label IS an SVG file: there is no template "
    "language, no layout DSL and no field substitution. A label that says "
    "VANILLE contains the text VANILLE, and its dates, quantities and "
    "percentages are in the document too. Making a new label means writing "
    "a new SVG and storing it here.\n"
    "\n"
    "Discovering what this device can do\n"
    "  Every command declares itself. `help describe` returns every "
    "category, every command and each command's arguments with types and "
    "descriptions, in one reply. Nothing about a command is written down "
    "twice, so what it returns is always this exact build. This text is "
    "only the part that does not fit in a declaration: which commands "
    "belong together, what order they go in, and what will not work.\n"
    "\n"
    "The usual order of work\n"
    "  1. `media list` - what label stock exists, and the dot geometry of "
    "each.\n"
    "  2. `fs list` on /labels, then `fs read` - existing designs, as style "
    "references.\n"
    "  3. `fs write` - the new SVG into /labels.\n"
    "  4. `render svg` - look at it. Nothing is consumed.\n"
    "  5. `print svg -media <id>` - put it on paper.\n"
    "  Steps 4 and 5 differ in kind, not in degree. Rendering is free and "
    "repeatable; printing advances the roll and spends a label that "
    "cannot be un-spent. Render first whenever the result can actually be "
    "inspected.\n"
    "\n"
    "The filesystem\n"
    "  A FAT partition with three directories, reached through the `fs` "
    "commands. Paths are rooted at the filesystem, not at the device: "
    "'/labels/vanilla.svg'. A '..' anywhere in a path is refused rather "
    "than resolved, and the three top-level directories are part of the "
    "device and cannot be deleted.\n"
    "    /labels  the label designs, one complete SVG file each.\n"
    "    /fonts   TrueType fonts the renderer may use. Read once, at boot.\n"
    "    /media   the label-stock definitions, one JSON file each. Go "
    "through the `media` commands rather than writing these by hand.\n"
    "  `fs list` shows a directory, `fs read` returns a file, `fs write` "
    "creates or replaces one, `fs delete` removes one, and `fs info` "
    "reports free space.\n"
    "\n"
    "File contents are NOT arguments\n"
    "  An argument list is capped at 512 bytes and a single value at 192, "
    "so an SVG does not fit in one and is not meant to. `fs write` takes "
    "the file's bytes as the request BODY, after the envelope line, in "
    "the same session. `fs read` and `render svg` reply the same way in "
    "reverse: a JSON header line, a newline, then raw bytes. There is no "
    "separate upload command and no chunking scheme to learn - it is the "
    "ordinary request and reply body.\n"
    "\n"
    "SVG, as THIS device draws it\n"
    "  The renderer is ThorVG, not a browser. It does the drawing part of "
    "SVG - shapes, paths, transforms, groups, fills including gradients, "
    "strokes, clip paths and opacity - and not the web platform around "
    "it. Do not rely on CSS stylesheets, script, foreignObject, filter "
    "effects, externally referenced images or web fonts; put presentation "
    "in ordinary SVG attributes on the elements themselves. Anything it "
    "does not understand it skips silently, so an unsupported feature "
    "costs a missing shape and no error message.\n"
    "  Give the root element a viewBox, and prefer a coordinate system "
    "where one user unit is one printer dot: draw at the medium's "
    "widthDots by heightDots, which `media list` reports. "
    "/labels/bc547.svg is that convention on the 25 mm square stock - "
    "width, height and viewBox all 295. Nothing enforces it, since a "
    "design is scaled to fit the stock anyway, but it makes every number "
    "in the file something you can measure on the paper.\n"
    "\n"
    "QR codes - declare the payload, never the modules\n"
    "  Do NOT generate QR modules yourself, and do not paste a matrix, a "
    "data: URI or a generator URL into a label. Write a rect that carries "
    "the PAYLOAD and this device encodes it, every time it renders:\n"
    "    <rect x=\"20\" y=\"20\" width=\"120\" height=\"120\" "
    "data-qr=\"https://parts.local/bc547\" data-qr-ecc=\"M\"/>\n"
    "  The device performs the encoding, the error correction and the "
    "module layout. A QR code is an error-correcting code rather than a "
    "drawing, so a matrix produced by anything that is not a QR encoder is "
    "not reliably correct - and a wrong one still SCANS, to the wrong "
    "address, on a label that is already stuck to something. The payload "
    "is the only part that is yours to choose.\n"
    "  Attributes:\n"
    "    data-qr       REQUIRED, and what makes the rect a placeholder. "
    "The text the code carries - a URL, an identifier, any string up to "
    "512 bytes. Escape it as XML: an & in a query string is &amp;.\n"
    "    data-qr-ecc   OPTIONAL, one of L, M, Q or H. Defaults to M. A "
    "higher level survives more damage but needs more modules, so raising "
    "it can stop a code fitting its box. Anything other than those four "
    "letters is an error rather than a silent fallback.\n"
    "    x, y, width, height   the BOX the code is fitted into, in the "
    "same user units as the rest of the drawing. x and y default to 0; "
    "width and height are required and must be positive.\n"
    "  The code is square and is sized by the SMALLER of width and "
    "height. Its module size is rounded DOWN to a whole number of dots "
    "and the result is centred in the box, so a box that does not divide "
    "evenly leaves a small even margin instead of blurring the modules - "
    "a module that is not a whole number of dots gets printed at two "
    "different widths and may not scan. The quiet zone, four modules on "
    "every side as the specification requires, is INSIDE the box and is "
    "painted white. So put nothing else inside that rectangle and do not "
    "add a margin of your own: the box you declare is the space the whole "
    "code occupies.\n"
    "  Sizing: the shorter side of the box must be at least (modules + 8) "
    "* 3 dots. A short URL at ECC M is commonly 25 to 33 modules, so "
    "allow roughly 99 to 123 dots - about 8 to 10 mm at 300 DPI. If the "
    "box is too small the render FAILS with a message naming the size "
    "that would have worked; enlarge the rect, shorten the payload, or "
    "lower data-qr-ecc. It never silently shrinks the modules, because a "
    "code that prints and does not scan is worse than one that does not "
    "print.\n"
    "  The rest of the rect is ignored: the element is replaced whole, so "
    "its fill, stroke and rx do nothing, and the code is drawn black on "
    "white. Put any caption in a separate <text> element outside the "
    "box.\n"
    "  This happens in `render svg` and `print svg` alike, so a preview "
    "shows the real code - scan the preview if you want to be certain "
    "before spending a label.\n"
    "\n"
    "Fonts, which are the part that surprises people\n"
    "  `render fonts` lists the fonts this device has registered. An SVG's "
    "font-family must match one of those names EXACTLY. A name comes from "
    "the filename in /fonts with the extension removed, so "
    "/fonts/DejaVuSans.ttf is font-family=\"DejaVuSans\". Nothing "
    "normalises case or spacing, there is no fallback font, and text "
    "whose font-family matches nothing renders as NOTHING AT ALL - the "
    "shapes around it still appear, so the label looks right except that "
    "the words are missing. Use the names `render fonts` gives and no "
    "others: a family copied out of a desktop design tool is the usual "
    "way to get a blank label. If text does not show up, check `render "
    "fonts` first. Adding a font is `fs write` to /fonts followed by "
    "`system reboot`; fonts are read once at startup.\n"
    "\n"
    "Rendering a preview\n"
    "  `render svg -path /labels/x.svg -width 400 -height 200` renders "
    "WITHOUT printing and returns the bitmap. Nothing is consumed and "
    "nothing moves, so it can be repeated as often as it is useful. The "
    "reply header gives width, height, format, stride and bytes, then the "
    "pixels follow after a newline. The format is ARGB8888S: one 32-bit "
    "little-endian word per pixel, so the bytes are blue, green, red, "
    "alpha, and alpha is not premultiplied. The SVG is scaled to fit the "
    "requested box with its aspect ratio preserved and centred; the "
    "header's 'scale' says by how much. The background defaults to opaque "
    "white because a label is printed on white paper.\n"
    "  To preview what a PRINT will look like, render at that medium's own "
    "widthDots and heightDots from `media list` - the same shape and the "
    "same scale as the printed dots. A box of some other aspect ratio "
    "previews the design but not the label.\n"
    "  Rendering is how you check your work. There is no other way to see "
    "what a label looks like, and a label that parses is not necessarily "
    "a label that reads well.\n"
    "\n"
    "Media - what the paper is\n"
    "  /labels holds SVG DESIGNS. /media holds definitions of physical "
    "LABEL STOCK: how big a roll is, and where it sits under the print "
    "head. The two are independent - a design is not tied to any "
    "particular stock, and a medium knows nothing about any design.\n"
    "  `media list` shows what stock this device knows, `media get` reads "
    "one, `media set` creates or updates one and `media delete` forgets "
    "one. Media are DATA, written at runtime: when a user says they "
    "bought labels that are 36 by 89 millimetres, that is one `media set` "
    "call and not a firmware change. Sizes are in MICROMETRES, so 36 mm "
    "is 36000.\n"
    "  A medium describes the paper and NEVER the printer. Resolution and "
    "print head width belong to the machine - they are the same for every "
    "roll anyone loads - and `print status` reports them. Do not put a "
    "dpi field on a medium and do not ask a user for one.\n"
    "  alignXUm and alignYUm are the PLACEMENT, and the only part of a "
    "medium that is a preference rather than a measurement. Zero is the "
    "right value until a printed calibration grid says otherwise: it "
    "puts the artwork on the first dot the machine can reach. Never "
    "invent one, and never derive one from the label dimensions - "
    "alignment does not follow from size. A new medium with zero "
    "alignment is honest and may print slightly off; a guessed one is "
    "wrong and looks deliberate. See the calibration section above for "
    "how to measure it.\n"
    "  marginLeftUm and marginTopUm are NOT alignment and NOT a way to "
    "move artwork. They are paper this particular roll loses beyond what "
    "the machine loses, they are non-negative, and they make the "
    "printable area SMALLER. Most rolls want 0. To shift what is on a "
    "label, change the alignment or change the SVG.\n"
    "  A medium written before this device told the printer and the "
    "paper apart still carries offsetXUm/offsetYUm, and `media get` "
    "reports legacyOffsets:true for it. It prints exactly where it "
    "always did; writing it once with `media set` converts it to "
    "alignment and clears the flag, without moving anything.\n"
    "  widthDots, heightDots, printableWidthDots and printableHeightDots "
    "come back with a medium but are DERIVED from its size and offsets at "
    "this printer's resolution, never stored. The printable pair is the "
    "smaller one because the offsets crop the design's top and left "
    "edges; anything that has to survive - a border, a line of text - "
    "belongs inside it.\n"
    "\n"
    "Calibration: three separate things, and only one of them is a "
    "preference\n"
    "  Getting a label to land correctly means knowing which of three "
    "things is wrong, because they have different owners and different "
    "fixes:\n"
    "    THE PRINTER   `printer get`. Its resolution, head width, and the "
    "strip along the left and leading edges the mechanism physically "
    "cannot print on - deadLeftUm and deadTopUm. A fact about the machine, "
    "the same for every roll. Measured once.\n"
    "    THE MEDIUM    `media get`. The label size, plus marginLeftUm and "
    "marginTopUm - any FURTHER strip this particular stock loses by sitting "
    "deeper in the guide than the rest. Usually 0. Non-negative: a margin "
    "is an amount of paper, not a direction.\n"
    "    THE ALIGNMENT alignXUm and alignYUm on the medium. Where the "
    "artwork sits. Signed, and it is the ONLY one of the three that is a "
    "choice rather than a measurement.\n"
    "  The rule that follows, and it matters:\n"
    "      printable = label size - printer dead zone - medium margin\n"
    "  Alignment is NOT in that. Moving the artwork never changes how much "
    "of the label can carry ink. If you find yourself changing an "
    "alignment to make a printable area come out right, the fix belongs in "
    "the printer or the medium instead.\n"
    "  With alignment at zero the artwork lands on the first dot the "
    "machine can reach, which is the correct value for a roll nobody has "
    "calibrated. Zero is honest. A guessed alignment is wrong and looks "
    "deliberate.\n"
    "\n"
    "How to calibrate a roll\n"
    "  1. `render svg -pattern calibration -width <widthDots> -height "
    "<heightDots>` using the medium's own dot size from `media list`. "
    "This costs nothing and shows exactly what step 2 will print.\n"
    "  2. `print svg -pattern calibration -media <id>` - one label.\n"
    "  3. Look at where the CENTRE MARKER landed. The grid has rings every "
    "25 dots from the middle of the design and heavier ones every 100, so "
    "the distance from the marker to the middle of the PAPER can be "
    "counted rather than measured. That distance, in dots, times 25400 and "
    "divided by the dpi, is the micrometres to add to alignXUm and "
    "alignYUm.\n"
    "  4. Try it without storing it: `print svg -pattern calibration "
    "-media <id> -offsetX <dots> -offsetY <dots>` overrides the placement "
    "for one job. Repeat until the marker is centred.\n"
    "  5. Store it: `media set -id <id> -alignXUm <um> -alignYUm <um>`.\n"
    "  If instead the ARTWORK is centred but part of the label never "
    "receives ink at all - a blank strip down the left or across the "
    "leading edge, on every roll - that is the printer's dead zone, not an "
    "alignment. Measure it and put it on the printer with `printer set "
    "-deadLeftUm/-deadTopUm`. If it happens on ONE roll only, it is that "
    "medium's marginLeftUm/marginTopUm.\n"
    "\n"
    "Built-in designs\n"
    "  `-pattern calibration` is the grid above; `-pattern test` is bars "
    "and a grey sweep for telling a printer fault from a label fault. Both "
    "take the place of -path on `render svg` and `print svg`, are generated "
    "at the size asked for, and go through the same renderer and placement "
    "a label does - so a preview of one is exactly what printing it "
    "produces.\n"
    "  `print test` and `print calibrate` are different and still there: "
    "they bypass the filesystem, the renderer and the medium entirely, "
    "which is what makes them able to tell a broken printer from a broken "
    "label. Reach for those when nothing prints at all.\n"
    "\n"
    "Designs and media are loosely coupled\n"
    "  Printing an SVG on a medium scales the design to the dot size of "
    "that medium, preserving aspect ratio, the same way `render svg` fits "
    "a box. So a design CAN be printed on stock it was not drawn for.\n"
    "  That is worth doing when the shapes are similar. When the aspect "
    "ratios differ substantially - a square design on a long thin roll - "
    "scaling leaves large empty margins and tiny text, and the right "
    "answer is a NEW SVG laid out for that shape rather than the old one "
    "squeezed into it. Read the old one, keep its style, redo its layout. "
    "Render it and look before deciding.\n"
    "\n"
    "Printing\n"
    "  `print svg -path /labels/x.svg -media <id>` renders the design and "
    "prints it. Name the medium: the size and the calibration come from "
    "it, so that is normally the whole call. Do not compute dots and do "
    "not copy a medium's numbers into the arguments.\n"
    "  This command is the physical one. It advances the roll and consumes "
    "a label, and there is no undo.\n"
    "  -width and -height in printer dots, and -offsetX and -offsetY, "
    "override the medium. They exist FOR CALIBRATION: printing one design "
    "at several offsets to find the right one. A settled value belongs in "
    "the medium via `media set`, not in every print call.\n"
    "  Check `print status` first. When nothing is attached, printing fails "
    "and says so; do not report a success you did not get. A reply "
    "carrying a `warning` field means the label came out BLANK, which is "
    "almost always an SVG naming a font-family the device does not have - "
    "compare it against `render fonts`.\n"
    "  `print test` prints a striped pattern and `print calibrate` prints a "
    "measuring grid. Neither uses the filesystem, the renderer or a "
    "medium, so they tell a printer problem from a label problem.\n"
    "\n"
    "Other things worth knowing\n"
    "  * `system reboot` answers first and then restarts about half a "
    "second later, so every connection drops and anything in flight is "
    "lost. It is also what makes a newly uploaded font take effect.\n"
    "  * The `partition` commands write flash and are for firmware updates. "
    "They are not the label filesystem; `fs` is.\n"
    "  * Argument values are strings, booleans and 32-bit integers, signed "
    "or unsigned as `help describe` says for each one. There is no "
    "floating-point argument anywhere in the protocol, which is why every "
    "size is a whole number of micrometres, dots or pixels.";

} // namespace DeviceDoc
